language: java

script:
  - mvn test -B -Dmatsim.preferLocalDtds=true
  - if ! [[ $( cat pom.xml | grep "SNAPSHOT" ) ]]; then if [[ $TRAVIS_BRANCH == $TRAVIS_TAG ]]; then mvn deploy -DskipTests=true --settings=settings.xml; fi; fi
